import { promises as Fs } from 'fs';
import * as Path from 'path';
import { Parser } from '../src/parser';

async function main() {
  const schemaPath = Path.resolve(__dirname, './json-schema-draft-07.json');
  const schemaData = await Fs.readFile(schemaPath, 'utf-8');
  const schema = JSON.parse(schemaData);
  const parser = new Parser({
    defaultUnknownPropertiesSchema: true,
  });

  parser.addSchema(`file://${schemaPath}`, schema);

  const { text } = parser.compile({
    topLevel: { isExported: true },
    lifted: { isExported: true },
  });

  const prelude = '// IMPORTANT: Do not edit this file by hand; it is automatically generated\n';

  await Fs.writeFile(Path.resolve(__dirname, '../src/schema.ts'), `${prelude}\n${text}`);
}

main().catch((err) => {
  console.trace(err);
  process.exit(1);
});
